CREATE TABLE Cars
(
    Guid UNIQUEIDENTIFIER PRIMARY KEY,
    Model VARCHAR(255) UNIQUE,
    TotalLength_mm INT,
    TotalWidth_mm INT,
    TotalHeight_mm INT,
    Wheelbase_mm INT,
    Acceleration_0_100_km_h_seconds DECIMAL(3,1),
    MaximumSpeed_km_h INT,
    Power_kW INT,
    BatteryCapacity_kWh DECIMAL(5,1),
    WLTP_Range_km INT,
    ChargingTime_0_100_AC VARCHAR(50),
    ChargingTime_10_80_DC VARCHAR(50),
    CurbWeight_kg INT,
    LoadCapacity_kg INT,
    TrunkCapacity_liters INT,
    ABSBrakes BIT,
    TractionControl BIT,
    LaneKeepingAssist BIT,
    Airbags BIT,
    AutomaticClimateControl BIT,
    IntegratedNavigationSystem BIT,
    ElectricallyAdjustableSeats BIT,
    GlassPanoramicRoof BIT,
    CentralTouchscreen_inches INT,
    BluetoothWiFiConnectivity BIT,
    PremiumSoundSystem BIT,
    AdjustableDrivingModes BIT,
    BasePrice_USD DECIMAL(10,2),
    NumberOfSeats INT
);
